server:
  port: 8084

spring:
  application:
    name: theatre-booking-service
  datasource:
    url: jdbc:h2:mem:testdb
    dbcp2:
      driver-class-name: org.h2.Driver
      username: test
      password: 

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    
    service-url:
      defaultZone: "http://localhost:8761/eureka"

management:
  tracing:
    sampling:
      probability: 1.0